import type { Metadata } from "next";
import { getBranding } from "@/lib/branding";

/**
 * Shared metadata builder for public pages. Produces a consistent `Metadata`
 * object — canonical (relative; resolved to absolute by the root layout's
 * `metadataBase`), Open Graph, Twitter card and `en_AU` locale — so each page
 * only declares its own title/description/path.
 *
 * Branding (`siteName`) is read through `getBranding()` only; nothing here
 * hardcodes a trading name (multi-tenant rule).
 *
 * OG/Twitter images point at the branded, generated `/opengraph-image` route
 * (src/app/opengraph-image.tsx) by default — referenced explicitly because
 * Next does not auto-merge the file-convention image once a page declares its
 * own `openGraph`. Pass `ogImage` to override per page.
 */
export interface BuildMetadataInput {
  /** Short page title; the root layout template appends `· {siteName}`. */
  title: string;
  description: string;
  /** Canonical path with a leading slash, e.g. `/fleet`. */
  path: string;
  keywords?: string[];
  /** Override the default branded OG image (absolute or root-relative). */
  ogImage?: string;
  ogType?: "website" | "article";
  /** Emit `noindex, follow` — for transactional / per-record pages. */
  noindex?: boolean;
}

/** Branded OG card generated by src/app/opengraph-image.tsx. */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

export async function buildMetadata(input: BuildMetadataInput): Promise<Metadata> {
  const { siteName } = await getBranding();
  const image = input.ogImage ?? DEFAULT_OG_IMAGE;
  return {
    title: input.title,
    description: input.description,
    keywords: input.keywords,
    alternates: { canonical: input.path },
    openGraph: {
      title: input.title,
      description: input.description,
      url: input.path,
      siteName,
      locale: "en_AU",
      type: input.ogType ?? "website",
      images: [{ url: image }],
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [image],
    },
    robots: input.noindex ? { index: false, follow: true } : undefined,
  };
}
