import { describe, expect, test, beforeEach } from "vitest";
import {
  generateTotpEnrolment,
  verifyTotpCode,
  verifyRecoveryCode,
} from "@/lib/totp";
import { TOTP, Secret } from "otpauth";

// The crypto module reads SECRET_ENC_KEY at first call. Set it once for
// the whole test run — must be 32 bytes encoded as base64.
beforeEach(() => {
  process.env.SECRET_ENC_KEY = Buffer.alloc(32, 7).toString("base64");
});

describe("generateTotpEnrolment", () => {
  test("returns a base32 secret, otpauth URL, and 10 recovery codes", () => {
    const e = generateTotpEnrolment("test@example.com");
    expect(e.secretBase32).toMatch(/^[A-Z2-7]+=*$/);
    expect(e.otpauthUrl).toContain("otpauth://totp/");
    expect(e.otpauthUrl).toContain(encodeURIComponent("XPERT Moto"));
    expect(e.otpauthUrl).toContain(encodeURIComponent("test@example.com"));
    expect(e.recoveryCodesPlain).toHaveLength(10);
    expect(e.hashedRecoveryCodes).toHaveLength(10);
    for (const code of e.recoveryCodesPlain) {
      expect(code).toMatch(/^[0-9a-f]{5}-[0-9a-f]{5}$/);
    }
  });

  test("recovery codes are unique per enrolment", () => {
    const a = generateTotpEnrolment("a@x.com");
    const b = generateTotpEnrolment("b@x.com");
    expect(new Set([...a.recoveryCodesPlain, ...b.recoveryCodesPlain]).size).toBe(20);
  });
});

describe("verifyTotpCode", () => {
  test("accepts a code generated by the same secret", () => {
    const e = generateTotpEnrolment("test@example.com");
    const totp = new TOTP({
      issuer: "XPERT Moto",
      label: "test@example.com",
      secret: Secret.fromBase32(e.secretBase32),
    });
    const code = totp.generate();
    expect(verifyTotpCode(code, e.encryptedSecret)).toBe(true);
  });

  test("rejects an invalid code", () => {
    const e = generateTotpEnrolment("test@example.com");
    expect(verifyTotpCode("000000", e.encryptedSecret)).toBe(false);
  });

  test("rejects non-6-digit input", () => {
    const e = generateTotpEnrolment("test@example.com");
    expect(verifyTotpCode("abcdef", e.encryptedSecret)).toBe(false);
    expect(verifyTotpCode("12345", e.encryptedSecret)).toBe(false);
    expect(verifyTotpCode("1234567", e.encryptedSecret)).toBe(false);
  });
});

describe("verifyRecoveryCode", () => {
  test("matches a hashed recovery code and returns its index", () => {
    const e = generateTotpEnrolment("test@example.com");
    const code = e.recoveryCodesPlain[2]!;
    const result = verifyRecoveryCode(code, e.hashedRecoveryCodes);
    expect(result.matched).toBe(true);
    if (result.matched) expect(result.index).toBe(2);
  });

  test("is case-insensitive + tolerates hyphens/spaces", () => {
    const e = generateTotpEnrolment("test@example.com");
    const code = e.recoveryCodesPlain[0]!.toUpperCase().replace("-", " ");
    expect(verifyRecoveryCode(code, e.hashedRecoveryCodes).matched).toBe(true);
  });

  test("rejects a made-up code", () => {
    const e = generateTotpEnrolment("test@example.com");
    expect(verifyRecoveryCode("00000-00000", e.hashedRecoveryCodes).matched).toBe(false);
  });

  test("rejects empty input without ever hashing", () => {
    const e = generateTotpEnrolment("test@example.com");
    expect(verifyRecoveryCode("", e.hashedRecoveryCodes).matched).toBe(false);
    expect(verifyRecoveryCode("   ", e.hashedRecoveryCodes).matched).toBe(false);
  });
});
