/**
 * One-off applier for customer addresses that the auto-resolver couldn't
 * handle. Each entry was hand-parsed from the original raw addressLine1.
 *
 * Dry-run by default; pass --apply to commit. Pass --customer-id <id> to
 * apply just one row.
 *
 * Convention:
 *   - addressLine1: street + unit/floor (best reading of the input)
 *   - suburb:       city / locality (international "city" goes here too)
 *   - state:        state / region / province (full name for non-AU)
 *   - postcode:     postcode in canonical local format
 *   - country:      ISO-style English name
 *   - skip: true    leave the row untouched (input is unsalvageable)
 *   - note:         freeform comment that gets logged
 */
import { PrismaClient } from "@prisma/client";

const p = new PrismaClient();

type Fix = {
  id: string;
  who: string;
  raw: string;
  addressLine1?: string;
  addressLine2?: string | null;
  suburb?: string;
  state?: string;
  postcode?: string;
  country?: string;
  skip?: true;
  note?: string;
};

// =============================================================================
// Hand-parsed mappings. Order matches the unresolved list.
// =============================================================================
const FIXES: Fix[] = [
  {
    id: "cmo5bmytb006x472kvfkastpq",
    who: "Igor Markovski",
    raw: "Suite 15,level 4",
    skip: true,
    note: "Only suite/floor info — no street/suburb. Contact customer.",
  },
  {
    id: "cmo5bmzll017p472kzxlfh623",
    who: "Marc Ebdrup",
    raw: "24635 105A Avenue Maple Ridge, BC V2W",
    addressLine1: "24635 105A Avenue",
    suburb: "Maple Ridge",
    state: "British Columbia",
    postcode: "V2W",
    country: "Canada",
    note: "Postcode is partial (3 chars); customer should confirm full FSA+LDU.",
  },
  {
    id: "cmo5bmzt401jh472kcl2c70yn",
    who: "Heath Whitacre",
    raw: "POB 1600 1600 Petersburg, Ala 99833",
    addressLine1: "PO Box 1600",
    suburb: "Petersburg",
    state: "Alaska",
    postcode: "99833",
    country: "United States",
  },
  {
    id: "cmo5bmzxj01ol472knl13xvyn",
    who: "Sam Kelly",
    raw: "26 Towne Place Queenstown, Otago Region 9300",
    addressLine1: "26 Towne Place",
    suburb: "Queenstown",
    state: "Otago",
    postcode: "9300",
    country: "New Zealand",
  },
  {
    id: "cmo5bn08o021t472kscazhrwq",
    who: "Remi Nadeau",
    raw: "5-572 Rue DAiguillon Quebec, Qc G1R1M3",
    addressLine1: "5-572 Rue D'Aiguillon",
    suburb: "Quebec City",
    state: "Quebec",
    postcode: "G1R 1M3",
    country: "Canada",
  },
  {
    id: "cmo5bn0bc025h472kzfpo4r62",
    who: "Oksana Kmiecik",
    raw: "8C Marcinow Marcinow,  57-360",
    addressLine1: "8C",
    suburb: "Marcinów",
    state: "Lower Silesian Voivodeship",
    postcode: "57-360",
    country: "Poland",
  },
  {
    id: "cmo5bn1qg02y9472k52kw6go0",
    who: "Tsubasa Nagaoka",
    raw: "Kuroki aza kamiizumi 23 106 Soma, Fukushima 9760052",
    addressLine1: "23-106 Kuroki aza Kamiizumi",
    suburb: "Soma",
    state: "Fukushima",
    postcode: "976-0052",
    country: "Japan",
  },
  {
    id: "cmo5bn2q103i1472k2q8chj0g",
    who: "test2 xpert",
    raw: "3 3, 13, 1, 1, 3",
    skip: true,
    note: "Test account — input is placeholder garbage.",
  },
  {
    id: "cmo5bn35l03t9472k16p5fqk1",
    who: "Andreas Seitz",
    raw: "199 Berrenrather Strasse Cologne, Nordrhine westfalia 50937",
    addressLine1: "199 Berrenrather Straße",
    suburb: "Cologne",
    state: "North Rhine-Westphalia",
    postcode: "50937",
    country: "Germany",
  },
  {
    id: "cmo5bn37603vx472ko551k5gk",
    who: "Bryan Freeman",
    raw: "09-371 Tampines St91 Singapore, Singapore 520933",
    addressLine1: "09-371 Tampines Street 91",
    suburb: "Singapore",
    state: "Singapore",
    postcode: "520933",
    country: "Singapore",
  },
  {
    id: "cmo5bn39703zl472kvav8nvhy",
    who: "Jan Al Jeffri Abdul Rashid",
    raw: "84 Jalan Datuk Sulaiman 4 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur 60000",
    addressLine1: "84 Jalan Datuk Sulaiman 4",
    suburb: "Kuala Lumpur",
    state: "Wilayah Persekutuan Kuala Lumpur",
    postcode: "60000",
    country: "Malaysia",
  },
  {
    id: "cmo5bn3cy0465472kztbm3kl6",
    who: "KAZUMA HIRAI",
    raw: "2728 Niyama-cho Akashi-shi, Hyogo 6730842",
    addressLine1: "2728 Niyama-cho",
    suburb: "Akashi",
    state: "Hyōgo",
    postcode: "673-0842",
    country: "Japan",
  },
  {
    id: "cmo5bn3p604cd472k9pvy7ofs",
    who: "Delhon Louis",
    raw: "202 Toritsudai flats Tairamachi, Meguro 1500",
    addressLine1: "202 Toritsudai Flats, Taira-machi",
    suburb: "Meguro",
    state: "Tokyo",
    postcode: "1500",
    country: "Japan",
    note: "Postcode 1500 is incomplete (Japanese postcodes are 7 digits XXX-XXXX) — customer should confirm.",
  },
  {
    id: "cmo5bn3t804ep472kh1syljrs",
    who: "YuHong Chen",
    raw: "9 Mavora Road Lake Hayes Estate, Otago Region 9304",
    addressLine1: "9 Mavora Road",
    suburb: "Lake Hayes Estate",
    state: "Otago",
    postcode: "9304",
    country: "New Zealand",
  },
  {
    id: "cmo5bn3vm04ht472k2kneesrb",
    who: "ALEXIUS LIM",
    raw: "3 Jalan Yasin Singapore, Bedok 417967",
    addressLine1: "3 Jalan Yasin",
    suburb: "Bedok",
    state: "Singapore",
    postcode: "417967",
    country: "Singapore",
  },
  {
    id: "cmo5bn3w604ix472kt46rzecv",
    who: "Jalajakshi Krishnappa",
    raw: "Motherwell, Scotland ML1 3FY",
    addressLine1: "(unknown — locality only)",
    suburb: "Motherwell",
    state: "Scotland",
    postcode: "ML1 3FY",
    country: "United Kingdom",
    note: "No street in input — addressLine1 placeholder; customer should fill street.",
  },
  {
    id: "cmo5bn3xq04m1472kkvfbszls",
    who: "Kazushige Moriyama",
    raw: "2846-1 Kanisawa, Toyono Nagano, Nagano 3891103",
    addressLine1: "2846-1 Kanisawa, Toyono",
    suburb: "Nagano",
    state: "Nagano",
    postcode: "389-1103",
    country: "Japan",
  },
  {
    id: "cmo5bn3y104ml472kpd0o9vvv",
    who: "David Hernandez Marcos",
    raw: "Sydney, Greenwich 2069",
    addressLine1: "(unknown — locality only)",
    suburb: "Greenwich",
    state: "NSW",
    postcode: "2069",
    country: "Australia",
    note: "No street — Greenwich (Sydney suburb) NSW 2069 only.",
  },
  {
    id: "cmo5bn41u04t9472k320z6omy",
    who: "Jinkyu Lee",
    raw: "249 Anyangcheonseo-ro Anyang-si, Gyung-gi-do 13995",
    addressLine1: "249 Anyangcheonseo-ro",
    suburb: "Anyang-si",
    state: "Gyeonggi-do",
    postcode: "13995",
    country: "South Korea",
  },
  {
    id: "cmo5bn41w04td472k3ms68xm0",
    who: "Ashish Tiwari",
    raw: "UNIT 2, 73-75 VICTORIA RD, WOY WOY NSW 2256 UNIT 2, 73-75 VICTORIA RD, WOY WOY NSW 2256 woy woy, nsw",
    addressLine1: "Unit 2, 73-75 Victoria Rd",
    suburb: "Woy Woy",
    state: "NSW",
    postcode: "2256",
    country: "Australia",
    note: "Input was duplicated — collapsed.",
  },
  {
    id: "cmo5bn45v050t472khimvddw2",
    who: "JIA WU",
    raw: "PANXI NEW VILLEGE SUZHOU, JIANGSU 215000",
    addressLine1: "Panxi New Village",
    suburb: "Suzhou",
    state: "Jiangsu",
    postcode: "215000",
    country: "China",
  },
  {
    id: "cmo5bn4dn055p472kdtx1adbq",
    who: "Yong joon Kim",
    raw: "70 Dobong-ro 13gil Gangbuk-gu, Seoul 01207",
    addressLine1: "70 Dobong-ro 13-gil",
    suburb: "Gangbuk-gu",
    state: "Seoul",
    postcode: "01207",
    country: "South Korea",
  },
  {
    id: "cmo5bn4ja058p472k52eld5t9",
    who: "Divay Joshi",
    raw: ",",
    skip: true,
    note: "Empty — just a comma. Contact customer.",
  },
  {
    id: "cmo5bn4rl05ct472k9rg2z3og",
    who: "WEI XIN",
    raw: "G3 lux street chengdu, sichuan 610000",
    addressLine1: "G3 Lux Street",
    suburb: "Chengdu",
    state: "Sichuan",
    postcode: "610000",
    country: "China",
  },
  {
    id: "cmo5bn4yy05gh472ki6iut2df",
    who: "Peter Adair",
    raw: "16 Edgcumbe Gardens Belfast, Northern Ireland BT4 2EG",
    addressLine1: "16 Edgcumbe Gardens",
    suburb: "Belfast",
    state: "Northern Ireland",
    postcode: "BT4 2EG",
    country: "United Kingdom",
  },
  {
    id: "cmo5bn59005s9472khlt8bvf8",
    who: "UMEDA KATSUSHIGE",
    raw: "1-25 Tamashimadai, Ibaraki Osaka, Osaka, 567-0848, Japan",
    addressLine1: "1-25 Tamashimadai",
    suburb: "Ibaraki",
    state: "Osaka",
    postcode: "567-0848",
    country: "Japan",
  },
  {
    id: "cmo5bn59805sl472kaf255bta",
    who: "KING MAN HUI",
    raw: "1-3 CLIFFTON ROAD, YAU MA TEI KOWLOON, / /",
    addressLine1: "1-3 Clifton Road",
    suburb: "Yau Ma Tei",
    state: "Kowloon",
    postcode: "",
    country: "Hong Kong",
    note: "Hong Kong does not use postcodes; left blank.",
  },
  {
    id: "cmo5bn5cu05zd472kkpktso2k",
    who: "Volker Capito",
    raw: "11 Suksawat 26 Chompthonng, Bangkok 10150",
    addressLine1: "11 Suksawat 26",
    suburb: "Chom Thong",
    state: "Bangkok",
    postcode: "10150",
    country: "Thailand",
  },
  {
    id: "cmo5bn5d005zp472k3y6l3nos",
    who: "SAMUELS TERRY",
    raw: "suite 401b/271 Sea Ray Avenue, Innisfil, ON, L9S 0J4, Canada",
    addressLine1: "Suite 401b/271 Sea Ray Avenue",
    suburb: "Innisfil",
    state: "Ontario",
    postcode: "L9S 0J4",
    country: "Canada",
  },
  {
    id: "cmo5bn5nc061t472kyqlmqyr9",
    who: "Kilyan Saez",
    raw: "790 on george 790 on george, Sydney, New south wales, 200, Australia",
    addressLine1: "790 George Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    country: "Australia",
    note: "Input duplicated and postcode truncated to '200' — corrected to 2000 (Sydney CBD).",
  },
  {
    id: "cmo5boedp06ot472kv8qjxn6l",
    who: "Markus Frembs",
    raw: "3 Uhdestraße Hannover, NDS 30171",
    addressLine1: "3 Uhdestraße",
    suburb: "Hannover",
    state: "Lower Saxony",
    postcode: "30171",
    country: "Germany",
  },
  {
    id: "cmo5bohjv06qj472kttijlrqa",
    who: "Walter Marcheselli",
    raw: "Rovigo, Veneto 45100",
    addressLine1: "(unknown — locality only)",
    suburb: "Rovigo",
    state: "Veneto",
    postcode: "45100",
    country: "Italy",
    note: "No street in input.",
  },
  {
    id: "cmo5boo1v06u7472kttxu4sed",
    who: "Clinci Alexandru",
    raw: "5 Mihail Bravu Bucharest, Bucharest 021325",
    addressLine1: "5 Mihail Bravu",
    suburb: "Bucharest",
    state: "Bucharest",
    postcode: "021325",
    country: "Romania",
  },
  {
    id: "cmo5botjc06xl472k56774sqm",
    who: "Vasilijs Zaremba",
    raw: "72A Nguyen Trai Hanoi, Hanoi 10000",
    addressLine1: "72A Nguyen Trai",
    suburb: "Hanoi",
    state: "Hanoi",
    postcode: "10000",
    country: "Vietnam",
  },
  {
    id: "cmo5bowqf06z5472k9bhcoe4m",
    who: "Marco Belzer",
    raw: "Fürth, BY 90768",
    addressLine1: "(unknown — locality only)",
    suburb: "Fürth",
    state: "Bavaria",
    postcode: "90768",
    country: "Germany",
    note: "No street in input.",
  },
  {
    id: "cmo5bpjwa07bb472klakorchm",
    who: "Michael Jordan",
    raw: "Pines Close Nottingham, England NG16",
    addressLine1: "Pines Close",
    suburb: "Nottingham",
    state: "England",
    postcode: "NG16",
    country: "United Kingdom",
    note: "Postcode partial (outward code only).",
  },
  {
    id: "cmo5bpkyv07bl472k166w4iyr",
    who: "Joshua Jordan",
    raw: "Pines Close Nottingham, England NG16",
    addressLine1: "Pines Close",
    suburb: "Nottingham",
    state: "England",
    postcode: "NG16",
    country: "United Kingdom",
    note: "Postcode partial (outward code only).",
  },
  {
    id: "cmo5bqku007t7472kdr3h8v45",
    who: "Ales Cervenka",
    raw: "K10 Zaguan del cielo Cusco, Cusco 08002",
    addressLine1: "K10 Zaguán del Cielo",
    suburb: "Cusco",
    state: "Cusco",
    postcode: "08002",
    country: "Peru",
  },
  {
    id: "cmo5bqp4a07v1472k6xccdr3u",
    who: "Mitsui Mari",
    raw: "211/81 Princes HWY St Peter, 211 2044",
    addressLine1: "211/81 Princes Highway",
    suburb: "St Peters",
    state: "NSW",
    postcode: "2044",
    country: "Australia",
    note: "Stray '211' before postcode appears to be a duplicated unit number.",
  },
  {
    id: "cmo5bqyeq07zf472kn48bff4s",
    who: "Tereza Lisa",
    raw: "509 Sadova Komarov, Czech 26762",
    addressLine1: "509 Sadová",
    suburb: "Komárov",
    state: "Central Bohemian Region",
    postcode: "267 62",
    country: "Czech Republic",
  },
  {
    id: "cmo5brc50087f472komvradh0",
    who: "Reuben Mac Curtain",
    raw: "puddle cottage Celbridge, Kildare w23 e0xw",
    addressLine1: "Puddle Cottage",
    suburb: "Celbridge",
    state: "County Kildare",
    postcode: "W23 E0XW",
    country: "Ireland",
  },
  {
    id: "cmo5brkbo08bl472k78256s7t",
    who: "Michael MacCurtain",
    raw: "Puddle Cottage, Killeenlea Celbridge Kildare, Co Kildare W23E0XW",
    addressLine1: "Puddle Cottage, Killeenlea",
    suburb: "Celbridge",
    state: "County Kildare",
    postcode: "W23 E0XW",
    country: "Ireland",
  },
  {
    id: "cmo5brork08e5472kaj9zbtj8",
    who: "Deepak Santhosh",
    raw: "FORTUNA CENTER PARK Bengaluru, KA 560097",
    addressLine1: "Fortuna Center Park",
    suburb: "Bengaluru",
    state: "Karnataka",
    postcode: "560097",
    country: "India",
  },
  {
    id: "cmo5bsp8w08z7472k8f1xfz9b",
    who: "David Chow",
    raw: "Unit C 18/F Tower 8 Island Resort 28 Siu Sai Wan Road Hong Kong, HKSAR NA",
    addressLine1: "Unit C, 18/F, Tower 8, Island Resort, 28 Siu Sai Wan Road",
    suburb: "Siu Sai Wan",
    state: "Hong Kong Island",
    postcode: "",
    country: "Hong Kong",
    note: "Hong Kong does not use postcodes.",
  },
  {
    id: "cmo5btejv09cr472kpjm0ucha",
    who: "MASAMI IWASA",
    raw: "14-2 Machihigasi, Yamadera Yamamoto-cho, Watari-gun,, Miyagi-ken, 989-2201, Japan",
    addressLine1: "14-2 Machihigashi, Yamadera, Yamamoto-cho",
    suburb: "Watari-gun",
    state: "Miyagi",
    postcode: "989-2201",
    country: "Japan",
  },
  {
    id: "cmo5bukwn0a0l472keq21z686",
    who: "eunsung park",
    raw: "342 Changwon-si, Gyeongsangnam-do 51111",
    addressLine1: "342",
    suburb: "Changwon-si",
    state: "Gyeongsangnam-do",
    postcode: "51111",
    country: "South Korea",
    note: "Street name absent — only building number '342'.",
  },
  {
    id: "cmo5bupfh0a2x472k0si25bfy",
    who: "TAMAKI TAKAKUWA",
    raw: "1-53-10 Minanisenju Arakawaku, Tokyo 1160003",
    addressLine1: "1-53-10 Minamisenju",
    suburb: "Arakawa",
    state: "Tokyo",
    postcode: "116-0003",
    country: "Japan",
  },
  {
    id: "cmo5buv4c0a5j472k138anx7i",
    who: "Keisuke Takakuwa",
    raw: "1-53-10 Minamisenju Arakawaku, Tokyo 1160003",
    addressLine1: "1-53-10 Minamisenju",
    suburb: "Arakawa",
    state: "Tokyo",
    postcode: "116-0003",
    country: "Japan",
  },
  {
    id: "cmo5buzrh0a7n472kgttequxd",
    who: "CHRISTIAN BUSTAMANTE",
    raw: "Alfredo Baquerizo Moreno N8-04 N8-04 Quito, CA 170802",
    addressLine1: "Alfredo Baquerizo Moreno N8-04",
    suburb: "Quito",
    state: "Pichincha",
    postcode: "170802",
    country: "Ecuador",
  },
  {
    id: "cmo5bvtpe0an3472kysg6ol9q",
    who: "Dov Cacoub",
    raw: "57, 3e esq Coelho da rocha Lisbon, Lisbon 1350 127",
    addressLine1: "Rua Coelho da Rocha 57, 3.º Esq.",
    suburb: "Lisbon",
    state: "Lisbon",
    postcode: "1350-127",
    country: "Portugal",
  },
  {
    id: "cmo5bvwu50aox472k2yl7032h",
    who: "Thomas Meyer",
    raw: "64 Am Turm, Siegburg, Germany, 53721, Germany",
    addressLine1: "64 Am Turm",
    suburb: "Siegburg",
    state: "North Rhine-Westphalia",
    postcode: "53721",
    country: "Germany",
  },
  {
    id: "cmo5bwef70ayv472kyfdau7df",
    who: "THIBAUD JEAN MARIE LOUGARE",
    raw: "529 o'connell street syndey, nsw 2000",
    addressLine1: "529 O'Connell Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    country: "Australia",
  },
  {
    id: "cmo5bwi320b0r472ki0hksyzz",
    who: "Michel LE TROADEC",
    raw: "Nouméa, New Caledonia 98800",
    addressLine1: "(unknown — locality only)",
    suburb: "Nouméa",
    state: "South Province",
    postcode: "98800",
    country: "New Caledonia",
    note: "No street in input.",
  },
  {
    id: "cmo5bwlt50b2d472k1aa55yhc",
    who: "Guofeng Tang",
    raw: "15-02 3 Meyer pl Singapore, Singapore 085501",
    addressLine1: "15-02, 3 Meyer Place",
    suburb: "Singapore",
    state: "Singapore",
    postcode: "085501",
    country: "Singapore",
    note: "Postcode '085501' is unusual for SG — customer should confirm.",
  },
  {
    id: "cmo5bwq7g0b4v472k503fvp9g",
    who: "Eduardo Rezende",
    raw: "1 Hellen Sydney, Nsw 2121",
    addressLine1: "1 Hellen Street",
    suburb: "Eastwood",
    state: "NSW",
    postcode: "2121",
    country: "Australia",
    note: "2121 is Eastwood; '1 Hellen' assumed to be Hellen Street.",
  },
  {
    id: "cmo5bwqa70b53472k32krq09m",
    who: "Nicolas Pidoux",
    raw: "304 Victoria street Darlinghust, Nsw 2010",
    addressLine1: "304 Victoria Street",
    suburb: "Darlinghurst",
    state: "NSW",
    postcode: "2010",
    country: "Australia",
  },
  {
    id: "cmo5bwt050b65472kdy2f62yc",
    who: "Petrus Smit",
    raw: "63 Swainston rd Saint John Auckland, Auckland 1072",
    addressLine1: "63 Swainston Road",
    suburb: "St Johns",
    state: "Auckland",
    postcode: "1072",
    country: "New Zealand",
  },
  {
    id: "cmo5bx1ho0bad472k60o58pij",
    who: "Clemens Kastner",
    raw: "City Walk, Building 10, Apt 506 Dubai, Dubai 12345",
    addressLine1: "City Walk, Building 10, Apt 506",
    suburb: "Dubai",
    state: "Dubai",
    postcode: "12345",
    country: "United Arab Emirates",
    note: "UAE doesn't really use postcodes; '12345' is a placeholder.",
  },
  {
    id: "cmo5bxl8a0bk7472kk4ys4ywq",
    who: "SEOKJIN HONG",
    raw: "284 7-4 Naengcheonro Pohang, GyeongBuk 37889",
    addressLine1: "284, 7-4 Naengcheon-ro",
    suburb: "Pohang",
    state: "Gyeongsangbuk-do",
    postcode: "37889",
    country: "South Korea",
  },
  {
    id: "cmo5bxw6h0bpj472k3l4pe1xp",
    who: "Nils Sorger",
    raw: "119 Kingstreet Sydney, NSW 454M+RJ",
    addressLine1: "119 King Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    country: "Australia",
    note: "Original postcode '454M+RJ' was a Plus Code — replaced with Sydney CBD 2000.",
  },
  {
    id: "cmo5by3nu0btd472ke3iak6sm",
    who: "Alexander Isaacs",
    raw: "1/22-4 Swete street Sydney, Nsw 2141",
    addressLine1: "1/22-4 Swete Street",
    suburb: "Lidcombe",
    state: "NSW",
    postcode: "2141",
    country: "Australia",
    note: "2141 covers Lidcombe / Berala area.",
  },
  {
    id: "cmo5by9aj0bw3472ksimy8k7v",
    who: "Mark William Mackay",
    raw: "573 Whakapirau Rd Hastings, Manawatu-Wanganui 4174",
    addressLine1: "573 Whakapirau Road",
    suburb: "Hastings",
    state: "Hawke's Bay",
    postcode: "4174",
    country: "New Zealand",
    note: "Customer wrote 'Manawatu-Wanganui' but 4174 is in Hawke's Bay region — corrected.",
  },
  {
    id: "cmo5bz3pf0c93472kpslitcsl",
    who: "SANGHYEON HAN",
    raw: "DongtanSunhwanDaeRo 710dong 1705ho Hwaseong-si, Gyeonggi 18470",
    addressLine1: "Dongtan Sunhwan-daero, 710-dong 1705-ho",
    suburb: "Hwaseong-si",
    state: "Gyeonggi-do",
    postcode: "18470",
    country: "South Korea",
  },
  {
    id: "cmo5bz9ol0cc7472kd5tvq3jf",
    who: "DAISUKE IBARAKI",
    raw: "3-18-26 National road no1 Chigasaki, Kanagawa 253-0045",
    addressLine1: "3-18-26 (off National Road No.1)",
    suburb: "Chigasaki",
    state: "Kanagawa",
    postcode: "253-0045",
    country: "Japan",
  },
  {
    id: "cmo5bzl7e0ci9472kjnynvava",
    who: "Yoji Yuzawa",
    raw: "4-15-7 Honjo Sumida, Tokyo 130-0004",
    addressLine1: "4-15-7 Honjo",
    suburb: "Sumida",
    state: "Tokyo",
    postcode: "130-0004",
    country: "Japan",
  },
  {
    id: "cmo5bzlpv0cij472kkspeuy8j",
    who: "MASASHI OKAMOTO",
    raw: "Shinjuku Shimoochiai 4-15-14, Tokyo 161-0033",
    addressLine1: "4-15-14 Shimoochiai",
    suburb: "Shinjuku",
    state: "Tokyo",
    postcode: "161-0033",
    country: "Japan",
  },
  {
    id: "cmo5bzpwt0ck9472knkz412fp",
    who: "YUKI ABE",
    raw: "2-5-15-201 Sakurashimmachi Setagayaku, Tokyo 1540015",
    addressLine1: "2-5-15-201 Sakurashinmachi",
    suburb: "Setagaya",
    state: "Tokyo",
    postcode: "154-0015",
    country: "Japan",
  },
  {
    id: "cmo5c07ce0csb472kbe5d02wy",
    who: "Lisa Meier",
    raw: "45 Charlottenbrunner Str. Berlin, Berlin 14193",
    addressLine1: "45 Charlottenbrunner Straße",
    suburb: "Berlin",
    state: "Berlin",
    postcode: "14193",
    country: "Germany",
  },
  {
    id: "cmo5c1mm30dit472ktqjrvijt",
    who: "Nurnatasha Binte Sharif",
    raw: "Singapore, Yishun 762461",
    addressLine1: "(unknown — locality only)",
    suburb: "Yishun",
    state: "Singapore",
    postcode: "762461",
    country: "Singapore",
    note: "No street in input.",
  },
  {
    id: "cmo5c1tn50dm1472k2owrhpn4",
    who: "Nishanth Jeevaganth",
    raw: "41 Worthing Road Singapore, Serangoon 554973",
    addressLine1: "41 Worthing Road",
    suburb: "Serangoon",
    state: "Singapore",
    postcode: "554973",
    country: "Singapore",
  },
  {
    id: "cmo5c3cz50eff472kdewhes0u",
    who: "MOONJONG KIM",
    raw: "Sentuem1 1 ?????, ????? 48060",
    addressLine1: "Sentuem 1",
    suburb: "(unknown — Korean characters were mangled)",
    state: "Busan",
    postcode: "48060",
    country: "South Korea",
    note: "Korean characters lost in import; postcode 48060 is in Busan.",
  },
  {
    id: "cmo5c4k3u0f4j472kdf30yrdj",
    who: "Sebastin Mieres gerhardt",
    raw: "26 Tkitimu Orkei, Akl 1071",
    addressLine1: "26 Takitimu Street",
    suburb: "Orakei",
    state: "Auckland",
    postcode: "1071",
    country: "New Zealand",
    note: "Spelling cleaned: Tkitimu→Takitimu, Orkei→Orakei.",
  },
  {
    id: "cmo5c61rw0fwl472kkegqyz9y",
    who: "Chit Bor Lam",
    raw: "???, ?? 852",
    skip: true,
    note: "All Chinese characters were lost in import. '852' is the country dialing code, not a postcode. Contact customer.",
  },
  {
    id: "cmo5c72o80ge5472kkhsvhn5f",
    who: "William Brenno",
    raw: "18 Skiferveien Oslo, Oslo 1151",
    addressLine1: "18 Skiferveien",
    suburb: "Oslo",
    state: "Oslo",
    postcode: "1151",
    country: "Norway",
  },
  {
    id: "cmo5c76f80gg9472kqsu4bqjg",
    who: "Ulrich Gehrer",
    raw: "2306 Rd42N Ile des chenes MB, canada R0A 0T3",
    addressLine1: "2306 Road 42N",
    suburb: "Île-des-Chênes",
    state: "Manitoba",
    postcode: "R0A 0T3",
    country: "Canada",
  },
  {
    id: "cmo5c76ml0ggj472kk5xy9hxf",
    who: "Alex Gehrer",
    raw: "23067 Rd42N Ile des chenes, MB R0A 0T3",
    addressLine1: "23067 Road 42N",
    suburb: "Île-des-Chênes",
    state: "Manitoba",
    postcode: "R0A 0T3",
    country: "Canada",
  },
  {
    id: "cmo5c7bqs0gin472kajoanlqe",
    who: "Robert Mccrodden",
    raw: "1675 Hwy 69 station pointe au Baril P0G 1K0 Pointe au Baril, Ontario P0G 1K0",
    addressLine1: "1675 Hwy 69, Station Pointe au Baril",
    suburb: "Pointe au Baril",
    state: "Ontario",
    postcode: "P0G 1K0",
    country: "Canada",
  },
  {
    id: "cmo5c7iyv0gmh472k127kyxi3",
    who: "Liam Jean",
    raw: "7 Akuna street Canberra, Act 2601",
    addressLine1: "7 Akuna Street",
    suburb: "Canberra",
    state: "ACT",
    postcode: "2601",
    country: "Australia",
  },
  {
    id: "cmo5c7r9e0gqr472kvmk08nb1",
    who: "Christopher Duckett",
    raw: "C4-09 Saigon South Ho Chi Minh, Nha Be 700000",
    addressLine1: "C4-09, Saigon South",
    suburb: "Nhà Bè",
    state: "Ho Chi Minh City",
    postcode: "700000",
    country: "Vietnam",
  },
  {
    id: "cmo5c7yvo0gul472kxvsn8y81",
    who: "Jean Paul Desrosiers",
    raw: "2100 Rue Paquette Drummondville, QC J2B",
    addressLine1: "2100 Rue Paquette",
    suburb: "Drummondville",
    state: "Quebec",
    postcode: "J2B",
    country: "Canada",
    note: "Postcode partial (FSA only).",
  },
  {
    id: "cmo5c8ht30h4j472kg5t4a7s1",
    who: "Yasuyuki TSUKUI",
    raw: "4-8-5 Kizuki Kawasaki, Kanagawa 211-0025",
    addressLine1: "4-8-5 Kizuki",
    suburb: "Kawasaki",
    state: "Kanagawa",
    postcode: "211-0025",
    country: "Japan",
  },
  {
    id: "cmo5c98tm0hil472k10p8hwif",
    who: "Tiarnan O'Kelly",
    raw: "44 Abington Malahide, D K36 X288",
    addressLine1: "44 Abington",
    suburb: "Malahide",
    state: "County Dublin",
    postcode: "K36 X288",
    country: "Ireland",
  },
  {
    id: "cmo5c9q0r0hr7472k8pashun2",
    who: "francois mermilliod",
    raw: "393 Joo Chiat Place Singapore, Bedok 428039",
    addressLine1: "393 Joo Chiat Place",
    suburb: "Bedok",
    state: "Singapore",
    postcode: "428039",
    country: "Singapore",
  },
  {
    id: "cmo5ca27z0hxb472kvabbobua",
    who: "Tamino Roemermann",
    raw: "13 Langer Wall Einbeck, NDS 37574",
    addressLine1: "13 Langer Wall",
    suburb: "Einbeck",
    state: "Lower Saxony",
    postcode: "37574",
    country: "Germany",
  },
  {
    id: "cmo5cbc1i0ijn472kkr554g7i",
    who: "Yuji Yoshitake",
    raw: "203 Hirao,5-14-25 Fukuoka, Fukuoka 8100014",
    addressLine1: "5-14-25 Hirao, Apt 203",
    suburb: "Fukuoka",
    state: "Fukuoka",
    postcode: "810-0014",
    country: "Japan",
  },
  {
    id: "cmo5ccb9g0j1r472k1y4f2ojq",
    who: "kazuho shibata",
    raw: "tokyo, ??? 1830034",
    addressLine1: "(unknown — Japanese characters were mangled)",
    suburb: "Fuchū",
    state: "Tokyo",
    postcode: "183-0034",
    country: "Japan",
    note: "Postcode 183-0034 is in Fuchū, Tokyo; street/building lost in import.",
  },
  {
    id: "cmo5ceej40k8z472k80x7i343",
    who: "Blas Esteban Calvo",
    raw: "Avenida General Quiroga 287 Quiroga, Buenos Aires 6533",
    addressLine1: "Avenida General Quiroga 287",
    suburb: "Quiroga",
    state: "Buenos Aires",
    postcode: "6533",
    country: "Argentina",
  },
  {
    id: "cmo5cei5z0kbb472kv3tn5vyo",
    who: "Aleksei Aristov",
    raw: "Unit 12 29-33 DUMARESQ ST Sydney, Nsw 2072",
    addressLine1: "Unit 12, 29-33 Dumaresq Street",
    suburb: "Gordon",
    state: "NSW",
    postcode: "2072",
    country: "Australia",
    note: "2072 is Gordon (Upper North Shore).",
  },
  {
    id: "cmo5cemd40kdv472kyivgax5f",
    who: "YEN LIANG LIN",
    raw: "Tamsui Dist 24F No 262 Sec 3 Xinshi 5th Rd Taipei, Taipei 251",
    addressLine1: "24F, No 262, Sec 3, Xinshi 5th Road, Tamsui Dist",
    suburb: "Tamsui District",
    state: "New Taipei City",
    postcode: "251",
    country: "Taiwan",
    note: "Tamsui is in New Taipei City, not Taipei City.",
  },
  {
    id: "cmo5cfiif0kwn472knox486mj",
    who: "Karun Mathew Joseph",
    raw: "18 Niemetzstr Berlin, Berlin 12055",
    addressLine1: "18 Niemetzstraße",
    suburb: "Berlin",
    state: "Berlin",
    postcode: "12055",
    country: "Germany",
  },
  {
    id: "cmo5cg11g0l9b472km0m8uuhr",
    who: "Rewanta Shakya",
    raw: "81-86 Courallie Ave, Unit 203A",
    addressLine1: "Unit 203A, 81-86 Courallie Avenue",
    suburb: "Homebush West",
    state: "NSW",
    postcode: "2140",
    country: "Australia",
    note: "Courallie Ave is in Homebush West NSW 2140; locality inferred from street.",
  },
  {
    id: "cmo5cg4ov0lbb472kcgcwe4vy",
    who: "Harjot Kaur",
    raw: "9b Essex street Syndey, Nsw 2148",
    addressLine1: "9B Essex Street",
    suburb: "Toongabbie",
    state: "NSW",
    postcode: "2148",
    country: "Australia",
    note: "2148 covers Toongabbie / Seven Hills area; 'Syndey' was a typo.",
  },
  {
    id: "cmo5cgnrq0lzz472ktrmve9em",
    who: "Chris Hagendyk",
    raw: "27a Victoria skye 1 muk ning street, New territories hk, Hong Kong2000",
    addressLine1: "27A Victoria Skye, 1 Muk Ning Street",
    suburb: "Kowloon City",
    state: "Kowloon",
    postcode: "",
    country: "Hong Kong",
    note: "Muk Ning Street is in Kowloon, not New Territories. HK has no postcodes.",
  },
  {
    id: "cmo5cgq150m5v472k7i5onzag",
    who: "Taiki Watanabe",
    raw: "Taito 1st-19-5-203, Taito ward, Tokyo1100016",
    addressLine1: "1-19-5-203 Taito",
    suburb: "Taito",
    state: "Tokyo",
    postcode: "110-0016",
    country: "Japan",
  },
  {
    id: "cmo5cgsa30me9472ktzlf0mz1",
    who: "Benjamin Jacob joinson FIRLEY",
    raw: "745 LEONINO RD, FLY CREEK, NT822",
    addressLine1: "745 Leonino Road",
    suburb: "Fly Creek",
    state: "NT",
    postcode: "0822",
    country: "Australia",
    note: "NT postcodes are 4 digits with leading zero — 822 → 0822.",
  },
  {
    id: "cmo5cgsjc0mft472k16jpihe7",
    who: "Honish SUNAR",
    raw: "9/65 WONIORA ROAD, HURSTVILLE, SYDNEY2220",
    addressLine1: "9/65 Woniora Road",
    suburb: "Hurstville",
    state: "NSW",
    postcode: "2220",
    country: "Australia",
  },
  {
    id: "cmo5cgt720mhj472k8rv69tos",
    who: "Osamu MARUKO",
    raw: "5-4 186 Hanakawaminami, Ishikari-city, Hokkaido061-3205",
    addressLine1: "5-4-186 Hanakawaminami",
    suburb: "Ishikari",
    state: "Hokkaido",
    postcode: "061-3205",
    country: "Japan",
  },
  {
    id: "cmo5cgtlu0mkn472kfhwvtgoi",
    who: "CARLOS RAMON GOMEZ HERNANDEZ",
    raw: ", ,",
    skip: true,
    note: "Empty placeholder. Contact customer.",
  },
  {
    id: "cmo5cgwci0mr7472kax4kx5yx",
    who: "Clement FOUQUERAY",
    raw: "13 Rue des couteliers, Naintre, French86530",
    addressLine1: "13 Rue des Couteliers",
    suburb: "Naintré",
    state: "Nouvelle-Aquitaine",
    postcode: "86530",
    country: "France",
    note: "'French' was misspelled 'France'; postcode 86530 is in Vienne dept.",
  },
];

// =============================================================================
// Applier
// =============================================================================
type Args = { apply: boolean; customerId?: string };

function parseArgs(argv: string[]): Args {
  const args: Args = { apply: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--apply") args.apply = true;
    else if (a === "--customer-id") {
      const v = argv[++i];
      if (!v) throw new Error("--customer-id requires a value");
      args.customerId = v;
    } else {
      throw new Error(`unknown argument: ${a}`);
    }
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const fixes = args.customerId
    ? FIXES.filter((f) => f.id === args.customerId)
    : FIXES;

  console.log(
    `${args.apply ? "APPLY" : "DRY-RUN"}: ${fixes.length} hand-parsed fix(es)`,
  );

  let updated = 0;
  let skipped = 0;
  let missing = 0;

  for (const f of fixes) {
    if (f.skip) {
      console.log(`  SKIP        ${f.id}  ${f.who}  "${f.raw}"`);
      console.log(`              ${f.note ?? ""}`);
      skipped++;
      continue;
    }

    const cp = await p.customerProfile.findUnique({ where: { id: f.id } });
    if (!cp) {
      console.log(`  MISSING     ${f.id}  ${f.who} — no CustomerProfile row`);
      missing++;
      continue;
    }

    console.log(
      `  ${args.apply ? "UPDATE" : "WOULD UPDATE"}  ${f.id}  ${f.who}\n` +
        `    from: "${cp.addressLine1 ?? ""}" | ${cp.suburb ?? "—"} | ${cp.state ?? "—"} | ${cp.postcode ?? "—"} | ${cp.country ?? "—"}\n` +
        `    to:   "${f.addressLine1 ?? ""}" | ${f.suburb ?? "—"} | ${f.state ?? "—"} | ${f.postcode ?? "—"} | ${f.country ?? "—"}` +
        (f.note ? `\n    note: ${f.note}` : ""),
    );

    if (args.apply) {
      await p.customerProfile.update({
        where: { id: f.id },
        data: {
          addressLine1: f.addressLine1 ?? undefined,
          addressLine2: f.addressLine2 ?? undefined,
          suburb: f.suburb ?? undefined,
          state: f.state ?? undefined,
          postcode: f.postcode ?? undefined,
          country: f.country ?? undefined,
        },
      });
      updated++;
    }
  }

  console.log("\n--- Summary ---");
  console.log(`Total fixes:    ${fixes.length}`);
  console.log(
    args.apply
      ? `Updated:        ${updated}`
      : `Would update:   ${fixes.length - skipped - missing}`,
  );
  console.log(`Skipped:        ${skipped}`);
  console.log(`Missing rows:   ${missing}`);
  if (!args.apply) {
    console.log("\nDry-run — re-run with --apply to commit.");
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => p.$disconnect());
