-- Add support chatbot notification types
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_ASSIGNED' BEFORE 'CUSTOM';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_URGENT' BEFORE 'CUSTOM';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_CUSTOMER_REPLY' BEFORE 'CUSTOM';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_RESOLVED' BEFORE 'CUSTOM';
